name 'prometheus'
maintainer 'ACME Platform'
maintainer_email 'platform@acme.test'
license 'Apache-2.0'
description 'Installs Prometheus node exporters for monitoring'
version '2.4.0'
chef_version '>= 16.0'
