name 'app'
maintainer 'ACME Platform'
maintainer_email 'platform@acme.test'
license 'Apache-2.0'
description 'Deploys the ACME application stack'
version '1.0.0'
chef_version '>= 16.0'
depends 'nginx'
depends 'postgresql'
