name 'haproxy'
maintainer 'ACME Platform'
maintainer_email 'platform@acme.test'
license 'Apache-2.0'
description 'Installs and configures the HAProxy load balancer'
version '12.2.1'
chef_version '>= 16.0'
