name 'postgresql'
maintainer 'ACME Platform'
maintainer_email 'platform@acme.test'
license 'Apache-2.0'
description 'Installs and configures the PostgreSQL database server'
version '11.1.0'
chef_version '>= 16.0'
